
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Senrith Fernando
 */
public class Display2 extends javax.swing.JFrame {
        String username="root";
        String password="";
        String dataCon="jdbc:mysql://localhost:3306/studentdb";
        
        Connection sqlCon=null;
        
        PreparedStatement pst=null;
        ResultSet rs=null;
    /**
     * Creates new form Display2
     */
    public Display2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_dc_code = new javax.swing.JTextField();
        txt_dc_name = new javax.swing.JTextField();
        txt_dc_sector = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_p_code = new javax.swing.JTextField();
        txt_p_name = new javax.swing.JTextField();
        txt_p_age = new javax.swing.JTextField();
        txt_p_tele = new javax.swing.JTextField();
        txt_p_sex = new javax.swing.JTextField();
        txt_p_address = new javax.swing.JTextField();
        txt_p_date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_p_about = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_p_drug = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 30, 562, -1));

        jLabel2.setText("Dc code");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 87, 55, -1));

        jLabel3.setText("Dc name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 115, 55, -1));

        jLabel4.setText("Sector");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 143, 55, -1));

        txt_dc_code.setEditable(false);
        getContentPane().add(txt_dc_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 84, 304, -1));

        txt_dc_name.setEditable(false);
        getContentPane().add(txt_dc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 112, 304, -1));

        txt_dc_sector.setEditable(false);
        getContentPane().add(txt_dc_sector, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 140, 304, -1));

        jLabel5.setText("P Code");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 87, 117, -1));

        jLabel6.setText("P name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 115, 117, -1));

        jLabel7.setText("Age");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 143, 117, -1));

        jLabel8.setText("Telephone");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 171, 117, -1));

        jLabel9.setText("Sex");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 199, 117, -1));

        jLabel10.setText("Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 227, 117, -1));

        jLabel11.setText("Date");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 255, 117, -1));

        txt_p_code.setEditable(false);
        getContentPane().add(txt_p_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 84, 498, -1));

        txt_p_name.setEditable(false);
        getContentPane().add(txt_p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 112, 498, -1));

        txt_p_age.setEditable(false);
        getContentPane().add(txt_p_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 140, 498, -1));

        txt_p_tele.setEditable(false);
        getContentPane().add(txt_p_tele, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 168, 498, -1));

        txt_p_sex.setEditable(false);
        getContentPane().add(txt_p_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 196, 498, -1));

        txt_p_address.setEditable(false);
        getContentPane().add(txt_p_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 224, 498, -1));

        txt_p_date.setEditable(false);
        getContentPane().add(txt_p_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 252, 498, -1));

        txta_p_about.setEditable(false);
        txta_p_about.setColumns(20);
        txta_p_about.setRows(5);
        jScrollPane1.setViewportView(txta_p_about);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 305, 519, 338));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("ABOUT PATIENT");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 283, 187, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("DRUG  DETAILS");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 283, 124, -1));

        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 671, 325, -1));

        jButton1.setText("Search - Patient Code");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 30, 210, -1));

        txta_p_drug.setEditable(false);
        txta_p_drug.setColumns(20);
        txta_p_drug.setRows(5);
        jScrollPane2.setViewportView(txta_p_drug);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 600, 340));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nurse gren .jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.setVisible(false);
        new Display01().setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlCon=DriverManager.getConnection("jdbc:mysql://localhost:3306/doctorpatient","root","");
            
            String query="SELECT code,name,age,sex,address,date,about,drug,telephne,dccode FROM patientdetails WHERE code=?";
                pst=sqlCon.prepareStatement(query);
                pst.setString(1,txt_search.getText());
                rs=pst.executeQuery();
                
                while(rs.next()){
                    
                    
                    txt_p_code.setText(rs.getString("code"));
                    txt_p_name.setText(rs.getString("name"));
                    txt_p_age.setText(rs.getString("age"));
                    txt_p_tele.setText(rs.getString("telephne"));
                    txt_p_sex.setText(rs.getString("sex"));
                    txt_p_address.setText(rs.getString("address"));
                    txt_p_date.setText(rs.getString("date"));
                    txta_p_about.setText(rs.getString("about"));
                    txta_p_drug.setText(rs.getString("drug"));
                    txt_dc_code.setText(rs.getString("dccode"));
                    
                    
                    
                    
                }
                
                 String query1="SELECT code,name,possision FROM doctor WHERE code=?";
                 pst=sqlCon.prepareStatement(query1);
                pst.setString(1,txt_dc_code.getText());
                rs=pst.executeQuery();
                
                while(rs.next()){
                        
                    txt_dc_name.setText(rs.getString("name"));
                    txt_dc_sector.setText(rs.getString("possision"));
                }
                
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Display2.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (SQLException ex) {
                Logger.getLogger(Display2.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_dc_code;
    private javax.swing.JTextField txt_dc_name;
    private javax.swing.JTextField txt_dc_sector;
    private javax.swing.JTextField txt_p_address;
    private javax.swing.JTextField txt_p_age;
    private javax.swing.JTextField txt_p_code;
    private javax.swing.JTextField txt_p_date;
    private javax.swing.JTextField txt_p_name;
    private javax.swing.JTextField txt_p_sex;
    private javax.swing.JTextField txt_p_tele;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextArea txta_p_about;
    private javax.swing.JTextArea txta_p_drug;
    // End of variables declaration//GEN-END:variables
}
