
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Senrith Fernando
 */
public class Login extends javax.swing.JFrame {
        String username="root";
        String password="";
        String dataCon="jdbc:mysql://localhost:3306/studentdb";
        
        Connection sqlCon=null;
        
        PreparedStatement pst=null;
        ResultSet rs=null;
        
        
        
        int x;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btn_log = new javax.swing.JButton();
        btn_reg = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txt_l_password = new javax.swing.JPasswordField();
        txt_l_uname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_dr_code = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_dr_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_dr_possisition = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_dr_tele = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_dr_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_dr_password = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_dr_repassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_log.setText("LOGIN");
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });
        jPanel3.add(btn_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 492, 227, 74));

        btn_reg.setText("REJISTER");
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });
        jPanel3.add(btn_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 610, 227, 73));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dc.jpg"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 610, 750));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 750));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_l_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_l_passwordActionPerformed(evt);
            }
        });
        jPanel4.add(txt_l_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 280, 50));
        jPanel4.add(txt_l_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 136, 278, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER NAME");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 140, 124, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 222, 124, 52));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/astrazeneca.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 480, 580));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dr Code");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dr Name");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dr Possision");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dr Telephone");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dr Email");

        txt_dr_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dr_emailActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dr Password");

        txt_dr_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dr_passwordActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dr Re-Password");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_dr_possisition)
                    .addComponent(txt_dr_tele)
                    .addComponent(txt_dr_name)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_dr_code)
                        .addComponent(txt_dr_email)
                        .addComponent(txt_dr_repassword)
                        .addComponent(txt_dr_password, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_dr_code)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_dr_name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_dr_possisition, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_dr_tele, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dr_email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_dr_password, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_dr_repassword, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(247, 247, 247))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 0, 570, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        x=1;
        
                txt_dr_code.setText("");
                txt_dr_name.setText("");
                txt_dr_possisition.setText("");
                txt_dr_tele.setText("");
                txt_dr_email.setText("");
                txt_dr_password.setText("");
                txt_dr_repassword.setText("");
                
                String uname=txt_l_uname.getText();
                String pword=txt_l_password.getText();
        
                if(x==1){
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlCon=DriverManager.getConnection("jdbc:mysql://localhost:3306/doctorpatient","root","");
                
                String query="SELECT  email, password FROM doctor WHERE email=?";
                pst=sqlCon.prepareStatement(query);
                pst.setString(1,txt_l_uname.getText());
                rs=pst.executeQuery();
                
                 while (rs.next()){
                      String uname1=rs.getString("email");
                      String pword1=rs.getString("password");
                      
                      if ((uname.equals(uname1))|| (pword.equals(pword1))|| (!uname.equals(null))){
//                          Display01 window= new Display01(txt_l_uname.getText());
                          
                          this.setVisible(false);
                          new Display01().setVisible(true);
//                          window.setVisible(true);
                          this.setVisible(false);
                          
                          txt_l_uname.setText("");
                          txt_l_password.setText("");
                          
                          JOptionPane.showMessageDialog(this,"Login Success");
                      }else{
                          JOptionPane.showMessageDialog(this,"Re-Check Password & User Name");
                      }
                 
                 }
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            x=0;
                }
    }//GEN-LAST:event_btn_logActionPerformed

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        
        txt_l_uname.setText("");
        txt_l_password.setText("");
        
        if(x==2){
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlCon=DriverManager.getConnection("jdbc:mysql://localhost:3306/doctorpatient","root","");
                
                String stNo1=txt_dr_code.getText();
                String stNo=null;
                
                String query1="SELECT code FROM doctor WHERE  code=? ";
                 stNo="";
                 
                pst=sqlCon.prepareStatement(query1);
                pst.setString(1,stNo1);
                rs=pst.executeQuery();
                
                while(rs.next()){
                     stNo=rs.getString("code");
                }
                if(stNo.equals(stNo1)){
                       JOptionPane.showMessageDialog(this,"Re-Check Dr code");

                             
                   }else{
                        String password1=txt_dr_password.getText();
                        String password2=txt_dr_repassword.getText();
                        String email=txt_dr_email.getText();
                        
                        
                        if(!email.equals("")&&(!email.equals(stNo))){
                 if((!password1.equals(""))&&(!password2.equals(""))){
                    if(password1.equals(password2)){
                        
                        String query="INSERT INTO doctor(code,name,possision,tele,email,password)VALUES(?,?,?,?,?,?)"; 
                         pst=sqlCon.prepareStatement(query);
                         
                        String code=txt_dr_code.getText();
                        String name=txt_dr_name.getText();
                        String address=txt_dr_possisition.getText();
                        String tele=txt_dr_tele.getText();
                        String emails=txt_dr_email.getText();
                        String password=txt_dr_password.getText();
                        
                        pst.setString(1, code);
                        pst.setString(2, name);
                        pst.setString(3, address);
                        pst.setString(4, tele);
                        pst.setString(5, emails);
                        pst.setString(6, password);
                        
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(this,"Rejister Successful");
                        
                        txt_dr_code.setText("");
                        txt_dr_name.setText("");
                        txt_dr_possisition.setText("");
                        txt_dr_tele.setText("");
                        txt_dr_email.setText("");
                        txt_dr_password.setText("");
                        txt_dr_repassword.setText("");
                    
                     jTabbedPane1.setSelectedIndex(0);
                        x=0;
                    
                    }else{
                        JOptionPane.showMessageDialog(this,"Re check Password ");
                        txt_dr_password.setText("");
                        txt_dr_repassword.setText("");
                        txt_dr_password.requestFocus();
                    
                    }}}
                
                }
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            x=0;
        }
        x=2;
        
    }//GEN-LAST:event_btn_regActionPerformed

    private void txt_dr_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dr_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dr_emailActionPerformed

    private void txt_dr_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dr_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dr_passwordActionPerformed

    private void txt_l_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_l_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_l_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_dr_code;
    private javax.swing.JTextField txt_dr_email;
    private javax.swing.JTextField txt_dr_name;
    private javax.swing.JTextField txt_dr_password;
    private javax.swing.JTextField txt_dr_possisition;
    private javax.swing.JTextField txt_dr_repassword;
    private javax.swing.JTextField txt_dr_tele;
    private javax.swing.JPasswordField txt_l_password;
    private javax.swing.JTextField txt_l_uname;
    // End of variables declaration//GEN-END:variables
}
